### ISSUE TITLE
Null Pointer Exception in the ConvivaVideoAnalytics.reportPlaybackMetric

### ISSUE THREAD

**Issue by vigneshwarannn** [Conviva/conviva-android-exoplayer#4]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.conviva.sdk.ConvivaVideoAnalytics.reportPlaybackMetric(java.lang.String, java.lang.Object[])' on a null object reference
       at com.conviva.playerinterface.ConvivaSDKExoPlayer.updatedMetrics(ConvivaSDKExoPlayer.java:65)
       at com.conviva.playerinterface.CVExoPlayerListener.lambda$updateMetrics$1(CVExoPlayerListener.java:235)
       at com.conviva.playerinterface.CVExoPlayerListener.$r8$lambda$uYyDachMW0JLkIu6PvFIMLrtK6w(CVExoPlayerListener.java)
       at com.conviva.playerinterface.CVExoPlayerListener$$InternalSyntheticLambda$1$1ee6395639ed10818a29deff6887fb849926c74e88d3a4e2807b481adea261c2$0.run(CVExoPlayerListener.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
       
       
       
       
 Getting the above crash for below dependency version

` implementation 'com.conviva.sdk:conviva-core-sdk:4.0.26' `   
 `implementation 'com.conviva.sdk:conviva-exoplayer-sdk:4.0.16'`

**Comment by rpconviva** [comment]
the videoAnalytics object is null , can you check wether it is initialised properly

**Comment by vigneshwarannn** [comment]
The analytics client object is held inside the SDK after initialisation, can u please let us know how the client object goes null inside the ConvivaSDKExoPlayer. Since there are no apis, to make that object null.

**Comment by rpconviva** [comment]
See as far as I can read it, the method is being called upon a null reference,

So my ask is to check whether it is Initialised properly before usage?

**Comment by rpconviva** [comment]
Please check if you have 

ConvivaVideoAnalytics videoAnalytics = 
    ConvivaAnalytics.buildVideoAnalytics(getApplicationContext());

This piece of code in your implementation

**Comment by vigneshwarannn** [comment]
Yes we have this code written in our init of our class, once initialised,
 why the instance inside the ConvivaSDKExoPlayer is getting null. ? 

init {
        Log.d(TAG, "initializing")
        checkAndInitializeConviva(context, apiKey, endpointURL, enableDebug)
        convivaVideoAnalytics = ConvivaAnalytics.buildVideoAnalytics(context)
        if (autoInitializeSession) {
            initSession()
        }
    }

**Comment by rpconviva** [comment]
Where is the instance of ConvivaSDKExoPlayer?

**Comment by vigneshwarannn** [comment]
we initialise only ConvivaVideoAnalytics. from the exception we could see the ConvivaVideoAnalytics instance inside the ConvivaSDKExoPlayer is getting null.

**Comment by malbanese** [comment]
I'm also seeing this exception on a limited number of users. When introspecting `ConvivaSDKExoPlayer.java`, it looks like there is a null check around the client inside the `updatedMetrics` method - however, we can see inside the `releaseModule` method that the client can get reset to null. 

Is it possible that two different threads are racing between these methods, and occasionally causing an error where the client is reset shortly after the null check, but before the other methods have run their course?

**Comment by SolarRage** [comment]
Hello. I have a similar error and it's still reproducing.
Perhaps you already have a solution?

**Comment by SarathRamachandra** [comment]
@malbanese @SolarRage @vigneshwarannn Sorry for the delay in response from our side.

Here is the release version which solves this issue for 2.18.1 Exo Player:
[v4.0.16.1](https://github.com/Conviva/conviva-android-exoplayer/releases/tag/v4.0.16.1) 

4.0.16.1 (07/JUN/2023)
Hot fix on top of Conviva Exo Player Module 4.0.16 fixing the thread synchronisation issues

Please let us know if you are using a different version other than this Exo Player version or Conviva Exo Player module prior, so that we can guide you to use the corresponding versions.
